
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 08 15:55:33 CDT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbol {
  /* terminals */
  public static final int GE = 10;
  public static final int NAMESPACE = 38;
  public static final int OUTPUT = 29;
  public static final int SLASH = 16;
  public static final int USING = 42;
  public static final int INPUT = 28;
  public static final int INTEGER = 3;
  public static final int LPAREN = 21;
  public static final int INT = 36;
  public static final int MINUS = 14;
  public static final int STD = 41;
  public static final int RPAREN = 22;
  public static final int NOT = 6;
  public static final int SEMICOLON = 18;
  public static final int AND = 4;
  public static final int LT = 7;
  public static final int OR = 5;
  public static final int COMMA = 20;
  public static final int CLASS = 31;
  public static final int IOSTREAM = 37;
  public static final int PLUS = 13;
  public static final int ASSIGN = 27;
  public static final int IF = 34;
  public static final int DOT = 19;
  public static final int ID = 2;
  public static final int LE = 8;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int error = 1;
  public static final int INCLUDE = 35;
  public static final int CIN = 30;
  public static final int EQ = 11;
  public static final int LBRACK = 23;
  public static final int TIMES = 15;
  public static final int COLON = 17;
  public static final int LBRACE = 25;
  public static final int ELSE = 33;
  public static final int COUT = 32;
  public static final int RBRACK = 24;
  public static final int WHILE = 43;
  public static final int PUBLIC = 39;
  public static final int RBRACE = 26;
  public static final int NE = 12;
  public static final int GT = 9;
}

